// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tNsmm9ZdBSrILTpcDDGGVyabEFBm8Q8',
    appId: '1:1073312766485:web:8c36d1623988fe31b4cc1c',
    messagingSenderId: '1073312766485',
    projectId: 'taxifood-f75ec',
    authDomain: 'taxifood-f75ec.firebaseapp.com',
    storageBucket: 'taxifood-f75ec.appspot.com',
    measurementId: 'G-VSC5P3T5B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYX_UM9a2dS5D8pUfgTBKanynA0iu9zPk',
    appId: '1:1073312766485:android:0c1f6cb4043392cdb4cc1c',
    messagingSenderId: '1073312766485',
    projectId: 'taxifood-f75ec',
    storageBucket: 'taxifood-f75ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCieYP3T7dqIK-ag16FDHjm5MWaBYf5P1o',
    appId: '1:1073312766485:ios:f63694b2f9c5125fb4cc1c',
    messagingSenderId: '1073312766485',
    projectId: 'taxifood-f75ec',
    storageBucket: 'taxifood-f75ec.appspot.com',
    iosBundleId: 'com.example.taxiFoodAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCieYP3T7dqIK-ag16FDHjm5MWaBYf5P1o',
    appId: '1:1073312766485:ios:f63694b2f9c5125fb4cc1c',
    messagingSenderId: '1073312766485',
    projectId: 'taxifood-f75ec',
    storageBucket: 'taxifood-f75ec.appspot.com',
    iosBundleId: 'com.example.taxiFoodAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9tNsmm9ZdBSrILTpcDDGGVyabEFBm8Q8',
    appId: '1:1073312766485:web:df8e67f85e6a4c72b4cc1c',
    messagingSenderId: '1073312766485',
    projectId: 'taxifood-f75ec',
    authDomain: 'taxifood-f75ec.firebaseapp.com',
    storageBucket: 'taxifood-f75ec.appspot.com',
    measurementId: 'G-QD4BRWEV0Y',
  );
}
